### ISSUE TITLE
platform.twitter.com

### ISSUE THREAD

**Issue by p1r473** [bentasker/adblocklists#1]
This domain breaks some tweets embedded in articles in Google News app on Android

**Comment by bentasker** [comment]
That's actually sort of by design - 80d32ab - having it unblocked allows Twitter's tracking.

The primary aim at the time (back in 2018) was blocking the "Tweet" buttons (just as Facebook's Like button etc are blocked), but it does now appear to have the spill-over effect of breaking some tweet embeds. 

Obviously it'd be easier if people [used screenshots instead of embedding](https://www.bentasker.co.uk/blog/opinion/481-screenshot-don-t-embed) but we can't control that.

I guess, really Social Media tracker domains (like platform.twitter.com) should be split out into a separate list - much like other upstreams do.

I'll have a fiddle about with it shortly

**Comment by p1r473** [comment]
This was the article I was using for testing
https://beincrypto.com/gold-price-falls-and-peter-schiff-blames-clueless-investors/
The bottom most tweet by Ari Paul is being blocked 
I had to unlock cdn.syndication.twimg.com on other lists (youre not blocking it) in order to see the content as well

I fully understand blocking tracking- just not a big fan of breaking/hiding legit content too
I have whitelisted it on my end but thought I'd report it anyways

**Comment by bentasker** [comment]
Cool thanks.

Yeah, I'd prefer to give a choice - I'm quite happy to have broken tweet embeds in my browser (most of the time), but I know others won't be.

I think the way I'm going at this is to leave the list as is (so that behaviour doesn't change for anyone else currently using the lists), but to have new copies generate with the social media trackers absent.

The code changes for that are (in theory) in place, I just need to go through the lists and identify the domains to move - there'll be some LinkedIn and Facebook in there too at the moment

**Comment by bentasker** [comment]
OK, there are now 3 new lists added here - https://www.bentasker.co.uk/adblock/index.html

- https://www.bentasker.co.uk/adblock/adblock_compiled_no_sm.txt
- https://www.bentasker.co.uk/adblock/easylist_modified_no_sm.txt
- https://www.bentasker.co.uk/adblock/social_media_trackers.txt

The first two are copies of the original lists, but with the social media paths moved out.

The `easylist_modified_no_sm.txt` does still contain some (heavily limited) `platform.twitter.com` lines from upstream - I've not interfered with those as they're limited to specific 1st party domains.

**Comment by bentasker** [comment]
Using this list - https://www.bentasker.co.uk/adblock/easylist_modified_no_sm.txt - my browser attempts to connect to platform.twitter.com when viewing your example article.

Admittedly it then fails because the change hasn't made it onto the adblock list on my DNS server yet.

**Comment by p1r473** [comment]
Thanks!

**Comment by p1r473** [comment]
Possible to provide it also in Pihole compatible format? (hosts file)
Not using ABP

**Comment by bentasker** [comment]
The twitter/social media domains should be excluded from the pihole file (though caches might not have expired quite yet on my CDN)

I was leaning toward leaving it that way too - with ABP lists you can choose to whitelist (if you're using the list with SM included), that's harder to do with DNS lists.

**Comment by bentasker** [comment]
Looks like it's cleared out of the list for me
```
ben@milleniumfalcon:~$ curl -s https://www.bentasker.co.uk/adblock/blockeddomains.txt | grep twitt
ads-twitter.com
ads.twitter.com
syndication.twitter.com
twittad.com
```

**Comment by bentasker** [comment]
On second thoughts, it doesn't really make sense not to provide one, so there's now a version of the Pihole list *with* Social media domains here - https://www.bentasker.co.uk/adblock/blocked_domains_with_sm.txt

**Comment by p1r473** [comment]
Thanks!
